spring:
  datasource:
    url: jdbc:h2:mem:userauth-jwt
    username: sa
    password:
    driver-class-name: org.h2.Driver
    schema: classpath:/sql/schema.sql
    data: classpath:/sql/data.sql
    platform: h2

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: update

config:
  oauth2:
    privatekey: -----BEGIN RSA PRIVATE KEY-----MIIEpAIBAAKCAQEApiMoluSCPDlFTyMPfaPH3hbzmzRyekypxg1yFdw/TlDV5ewLIIYm858eyndjWdOYiNDJLodaj0n+sdRsau15ohbHKJUBdqeo/RHbxtS8euBNluPOvhegQgEjmK/5+iL4527HSo0gWRie8f7/U9EKYF+cCwjAj/9OtTniTYbPWhdPkrMxzbx6/r5S+urvXfv9UcKGNpdakEkAfWP7Z81/FzXFsHW4oWRuUTQdw6IZ1erKZTid8rEldqxke9gtleo3d3lvqc897mPeToSDnRhWv5wIObRupSZ5Ptfn/a5RS57mn7HuS+5Mg1E9GIpk2Xj1sNqRSxlcu+oxzFrjFcrc4QIDAQABAoIBAQCLJP00y7PMDsdezWWG++pEtwJWpimPBrBWgSJg7rNSu186j2SOW+05s7ZNKoraS98AD6W/w3t0cSvQ8rHPKI/r0poBAjNUln1xX0isEba+TyiMzMV17kG5pkyS8Cg0eJ/w7ZYaeXJzTKyqz8A3Cehf6RO/JhhpQhJAtHc2KUd3EpqVweQJpfolbcxohBCc92xEcvy8wRs5INi4mLuCvBDhp9h1cpgVnRSOTu3tEU/NkMg37T01GLs839YN46h+Z/bgmiL1frvbIwhWCK2JswhZHBxEYj9/e1Ph+dRAzbmKfiZsbf1KBA13m7fD2KewoVXpdS6RIUVU4E9As9RfhAGxAoGBAPRMwmHDPPs4MLCWTfcNNcX6bUGQUG3OOCoZc8dIPnNsAOqX4mCShcdQaRl99nmnvh6MNweXCB1Ndb9t53MVzXSDT/kvKx827eoawRXRpYtqsLIZnRM3xRhGbfZVvpEKdM4sAJZapU3KffahN6WWjeKVUOPFlZ38yVMrnm6pBlldAoGBAK4YFksOGAjq2mT/96fHNLyloWND04d/bnUyMyGDDDIDMXzpIP2V7YjE/oF1HHApLAiH/bmWiKE6sZF/8CrEKqw81fAiriaItuSFi7vgf7VjGtsRtbjuesSGmvOnZUbGrSTQOUfS6D0rVq43x42upD7IJoRtCyk1x/qJdTxcy+VVAoGBAMvJoDjHEX6Kn+seZokYhuvQfAU+Kil+5dEQjEkHlbjYtmb7LgbbEydxh0qRjeJrsCdxVZJKRaWT8Q4v0utom4t+4l5+H12Zh5tKmBjoWkzTQfQ/c40Nb6dRUPc1DZOWAlvdztudX9llefAbCf1iepcxcVmff7Bbp2FuuGmdK8OtAoGACpHl0JrDdM8lgVpVI/ehSQ7ZVJiKoEBpaW4p0pANToAJIidZXGwc5t/m/98nYdvuE3qGOh1coEVbAJV+9GnCmYB8EL9aSXalfAxrpnWD63Rf7gsOOHMqOwJdKAvyxzBK1OBbifPRK92UvrEeSYjf6fvm8sVYFyFvydNMreSIcJ0CgYAxE5brXmO/9IW2WpGnKenkp5azfmLktsF6mImiNoXRmgyPOH9Fy2w7UeXpRsw8IhgLXwgqE64xHjg/I1cAebBi1JkvId2HC0mVVd/z1RgQSAFLfMVWzhi7Ktm2JVQYePQ6c23/RyjsHx8Z1iI5QQlhEOkqcKFm2/aGUIGA9Enu1w==-----END RSA PRIVATE KEY-----
    publickey: -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApiMoluSCPDlFTyMPfaPH3hbzmzRyekypxg1yFdw/TlDV5ewLIIYm858eyndjWdOYiNDJLodaj0n+sdRsau15ohbHKJUBdqeo/RHbxtS8euBNluPOvhegQgEjmK/5+iL4527HSo0gWRie8f7/U9EKYF+cCwjAj/9OtTniTYbPWhdPkrMxzbx6/r5S+urvXfv9UcKGNpdakEkAfWP7Z81/FzXFsHW4oWRuUTQdw6IZ1erKZTid8rEldqxke9gtleo3d3lvqc897mPeToSDnRhWv5wIObRupSZ5Ptfn/a5RS57mn7HuS+5Mg1E9GIpk2Xj1sNqRSxlcu+oxzFrjFcrc4QIDAQAB-----END PUBLIC KEY-----